pull_request_rules:
  - name: Automatic merge on CI
    conditions:
      - status-success=continuous-integration/travis-ci/push
    actions:
      merge:
        method: merge
        strict: true
      delete_head_branch: