pull_request_rules:
  - name: Automatic merge on CI success
    conditions:
      - status-success=Travis CI - Pull Request
    actions:
      merge:
        method: merge
        strict: true
      delete_head_branch: