pull_request_rules:
  - name: Automatic merge on CI success
    conditions:
      - status-success=continuous-integration/travis-ci/pr
      - "#approved-reviews-by>=0"
    actions:
      merge:
        method: merge
        strict: true
      delete_head_branch: