
matrix:
  include:
    - language: node_js
      node_js:
        - node # get latest node version available in travis
      cache: npm # cache installed npm packages for faster build times.
      dist: trusty # uses trusty environment
      sudo: false # when on trusty, uses Docker containers for speed
      # before_install:
      #   cd client
      # install:
      #   - npm ci # faster, goes only from package-lock
      # before_script:
      #   - cd client
      script:
         - echo "i ran"
        # - npm run lint
        # - npm run test-headless
    # - language: csharp
    #   dotnet: 2.2.103
    #   install:
    #     - dotnet restore
    #   before_script:
    #     - cd server
    #   script:
    #     - dotnet build
    #     - dotnet test MTAServiceStatus.Tests/MTAServiceStatus.Tests.csproj

    