version: '3.7'

services:
  nginx:
    image: nginx:stable-alpine
    restart: always
    environment:
      - NGINX_HOST=${NGINX_HOST}
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./client/dist/www:/usr/share/nginx/html
    command: nginx -g 'daemon off';
  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile