version: '3.7'

services:
  client:
    build:
      context: ./client
      dockerfile: ./client/Dockerfile
    volumes:
      - static-web:./client/dist
  nginx:
    image: nginx:stable-alpine
    restart: always
    environment:
      - NGINX_HOST=${NGINX_HOST}
    ports:
      - 80:80
    volumes:
      - ./nginx/template.conf:/tmp/template.conf
      - static-web:/usr/share/nginx/html
    command: /bin/sh -c "envsubst '$$NGINX_HOST' < /tmp/template.conf > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
  server:
    build:
      context: ./server
      dockerfile: ./server/Dockerfile
volumes:
  static-web: