export const popularMovies = {
  page: 1,
  total_results: 19833,
  total_pages: 992,
  results: [
    {
      vote_count: 967,
      id: 399579,
      video: false,
      vote_average: 6.8,
      title: "Alita: Battle Angel",
      popularity: 379.529,
      poster_path: "/xRWht48C2V8XNfzvPehyClOvDni.jpg",
      original_language: "en",
      original_title: "Alita: Battle Angel",
      genre_ids: [28, 878, 53],
      backdrop_path: "/aQXTw3wIWuFMy0beXRiZ1xVKtcf.jpg",
      adult: false,
      overview:
        "When Alita awakens with no memory of who she is in a future world she does not recognize, she is taken in by Ido, a compassionate doctor who realizes that somewhere in this abandoned cyborg shell is the heart and soul of a young woman with an extraordinary past.",
      release_date: "2019-01-31"
    },
    {
      vote_count: 1595,
      id: 490132,
      video: false,
      vote_average: 8.4,
      title: "Green Book",
      popularity: 271.893,
      poster_path: "/7BsvSuDQuoqhWmU2fL7W2GOcZHU.jpg",
      original_language: "en",
      original_title: "Green Book",
      genre_ids: [18, 35, 10402],
      backdrop_path: "/78PjwaykLY2QqhMfWRDvmfbC6EV.jpg",
      adult: false,
      overview:
        "Tony Lip, a bouncer in 1962, is hired to drive pianist Don Shirley on a tour through the Deep South in the days when African Americans, forced to find alternate accommodations and services due to segregation laws below the Mason-Dixon Line, relied on a guide called The Negro Motorist Green Book.",
      release_date: "2018-11-16"
    },
    {
      vote_count: 1974,
      id: 324857,
      video: false,
      vote_average: 8.5,
      title: "Spider-Man: Into the Spider-Verse",
      popularity: 248.334,
      poster_path: "/iiZZdoQBEYBv6id8su7ImL0oCbD.jpg",
      original_language: "en",
      original_title: "Spider-Man: Into the Spider-Verse",
      genre_ids: [28, 12, 16, 878, 35],
      backdrop_path: "/7d6EY00g1c39SGZOoCJ5Py9nNth.jpg",
      adult: false,
      overview:
        'Miles Morales is juggling his life between being a high school student and being a spider-man. When Wilson "Kingpin" Fisk uses a super collider, others from across the Spider-Verse are transported to this dimension.',
      release_date: "2018-12-07"
    },
    {
      vote_count: 1549,
      id: 450465,
      video: false,
      vote_average: 6.7,
      title: "Glass",
      popularity: 233.509,
      poster_path: "/svIDTNUoajS8dLEo7EosxvyAsgJ.jpg",
      original_language: "en",
      original_title: "Glass",
      genre_ids: [53, 9648, 18, 14],
      backdrop_path: "/lvjscO8wmpEbIfOEZi92Je8Ktlg.jpg",
      adult: false,
      overview:
        "In a series of escalating encounters, security guard David Dunn uses his supernatural abilities to track Kevin Wendell Crumb, a disturbed man who has twenty-four personalities. Meanwhile, the shadowy presence of Elijah Price emerges as an orchestrator who holds secrets critical to both men.",
      release_date: "2019-01-16"
    },
    {
      vote_count: 5532,
      id: 424694,
      video: false,
      vote_average: 8.1,
      title: "Bohemian Rhapsody",
      popularity: 175.202,
      poster_path: "/lHu1wtNaczFPGFDTrjCSzeLPTKN.jpg",
      original_language: "en",
      original_title: "Bohemian Rhapsody",
      genre_ids: [18, 10402],
      backdrop_path: "/93xA62uLd5CwMOAs37eQ7vPc1iV.jpg",
      adult: false,
      overview:
        "Singer Freddie Mercury, guitarist Brian May, drummer Roger Taylor and bass guitarist John Deacon take the music world by storm when they form the rock 'n' roll band Queen in 1970. Hit songs become instant classics. When Mercury's increasingly wild lifestyle starts to spiral out of control, Queen soon faces its greatest challenge yet – finding a way to keep the band together amid the success and excess.",
      release_date: "2018-10-24"
    },
    {
      vote_count: 753,
      id: 166428,
      video: false,
      vote_average: 8,
      title: "How to Train Your Dragon: The Hidden World",
      popularity: 165.599,
      poster_path: "/xvx4Yhf0DVH8G4LzNISpMfFBDy2.jpg",
      original_language: "en",
      original_title: "How to Train Your Dragon: The Hidden World",
      genre_ids: [16, 10751, 12],
      backdrop_path: "/h3KN24PrOheHVYs9ypuOIdFBEpX.jpg",
      adult: false,
      overview:
        "As Hiccup fulfills his dream of creating a peaceful dragon utopia, Toothless’ discovery of an untamed, elusive mate draws the Night Fury away. When danger mounts at home and Hiccup’s reign as village chief is tested, both dragon and rider must make impossible decisions to save their kind.",
      release_date: "2019-01-03"
    },
    {
      vote_count: 1435,
      id: 480530,
      video: false,
      vote_average: 6.6,
      title: "Creed II",
      popularity: 157.279,
      poster_path: "/v3QyboWRoA4O9RbcsqH8tJMe8EB.jpg",
      original_language: "en",
      original_title: "Creed II",
      genre_ids: [18],
      backdrop_path: "/8yqLPNwNCtpOPc3XkOlkSMnghzw.jpg",
      adult: false,
      overview:
        "Between personal obligations and training for his next big fight against an opponent with ties to his family's past, Adonis Creed is up against the challenge of his life.",
      release_date: "2018-11-21"
    },
    {
      vote_count: 3542,
      id: 338952,
      video: false,
      vote_average: 6.9,
      title: "Fantastic Beasts: The Crimes of Grindelwald",
      popularity: 135.495,
      poster_path: "/kQKcbJ9uYkTQql2R8L4jTUz7l90.jpg",
      original_language: "en",
      original_title: "Fantastic Beasts: The Crimes of Grindelwald",
      genre_ids: [10751, 14, 12],
      backdrop_path: "/wDN3FIcQQ1HI7mz1OOKYHSQtaiE.jpg",
      adult: false,
      overview:
        "Gellert Grindelwald has escaped imprisonment and has begun gathering followers to his cause—elevating wizards above all non-magical beings. The only one capable of putting a stop to him is the wizard he once called his closest friend, Albus Dumbledore. However, Dumbledore will need to seek help from the wizard who had thwarted Grindelwald once before, his former student Newt Scamander, who agrees to help, unaware of the dangers that lie ahead. Lines are drawn as love and loyalty are tested, even among the truest friends and family, in an increasingly divided wizarding world.",
      release_date: "2018-11-14"
    },
    {
      vote_count: 4082,
      id: 332562,
      video: false,
      vote_average: 7.5,
      title: "A Star Is Born",
      popularity: 131.703,
      poster_path: "/wrFpXMNBRj2PBiN4Z5kix51XaIZ.jpg",
      original_language: "en",
      original_title: "A Star Is Born",
      genre_ids: [18, 10402, 10749],
      backdrop_path: "/wqtaHWOEZ3rXDJ8c6ZZShulbo18.jpg",
      adult: false,
      overview:
        "Seasoned musician Jackson Maine discovers — and falls in love with — struggling artist Ally. She has just about given up on her dream to make it big as a singer — until Jack coaxes her into the spotlight. But even as Ally's career takes off, the personal side of their relationship is breaking down, as Jack fights an ongoing battle with his own internal demons.",
      release_date: "2018-10-03"
    },
    {
      vote_count: 1270,
      id: 375262,
      video: false,
      vote_average: 7.7,
      title: "The Favourite",
      popularity: 119.152,
      poster_path: "/cwBq0onfmeilU5xgqNNjJAMPfpw.jpg",
      original_language: "en",
      original_title: "The Favourite",
      genre_ids: [18, 36, 35],
      backdrop_path: "/ekWMoBZ4B9rM60INZEh5FAD2HFR.jpg",
      adult: false,
      overview:
        "England, early 18th century. The close relationship between Queen Anne and Sarah Churchill is threatened by the arrival of Sarah's cousin, Abigail Hill, resulting in a bitter rivalry between the two cousins to be the Queen's favourite.",
      release_date: "2018-11-23"
    },
    {
      vote_count: 81,
      id: 452832,
      video: false,
      vote_average: 4.8,
      title: "Serenity",
      popularity: 110.926,
      poster_path: "/hgWAcic93phg4DOuQ8NrsgQWiqu.jpg",
      original_language: "en",
      original_title: "Serenity",
      genre_ids: [53, 18, 9648, 878],
      backdrop_path: "/oOROXoQ402tHgK6NowmMUSLffkW.jpg",
      adult: false,
      overview:
        "Baker Dill is a fishing boat captain leading tours off a tranquil, tropical enclave called Plymouth Island. His quiet life is shattered, however, when his ex-wife Karen tracks him down with a desperate plea for help.",
      release_date: "2019-01-24"
    },
    {
      vote_count: 1543,
      id: 404368,
      video: false,
      vote_average: 7.3,
      title: "Ralph Breaks the Internet",
      popularity: 109.957,
      poster_path: "/ybhsGCKHpzqJDRsfnGmHNUHHrqB.jpg",
      original_language: "en",
      original_title: "Ralph Breaks the Internet",
      genre_ids: [10751, 16, 35, 14],
      backdrop_path: "/88poTBTafMXaz73vYi3c74g0y2k.jpg",
      adult: false,
      overview:
        'Video game bad guy Ralph and fellow misfit Vanellope von Schweetz must risk it all by traveling to the World Wide Web in search of a replacement part to save Vanellope\'s video game, "Sugar Rush." In way over their heads, Ralph and Vanellope rely on the citizens of the internet -- the netizens -- to help navigate their way, including an entrepreneur named Yesss, who is the head algorithm and the heart and soul of trend-making site BuzzzTube.',
      release_date: "2018-11-20"
    },
    {
      vote_count: 11656,
      id: 299536,
      video: false,
      vote_average: 8.3,
      title: "Avengers: Infinity War",
      popularity: 109.758,
      poster_path: "/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg",
      original_language: "en",
      original_title: "Avengers: Infinity War",
      genre_ids: [12, 28, 14],
      backdrop_path: "/bOGkgRGdhrBYJSLpXaxhXVstddV.jpg",
      adult: false,
      overview:
        "As the Avengers and their allies have continued to protect the world from threats too large for any one hero to handle, a new danger has emerged from the cosmic shadows: Thanos. A despot of intergalactic infamy, his goal is to collect all six Infinity Stones, artifacts of unimaginable power, and use them to inflict his twisted will on all of reality. Everything the Avengers have fought for has led up to this moment - the fate of Earth and existence itself has never been more uncertain.",
      release_date: "2018-04-25"
    },
    {
      vote_count: 3839,
      id: 297802,
      video: false,
      vote_average: 6.8,
      title: "Aquaman",
      popularity: 97.755,
      poster_path: "/5Kg76ldv7VxeX9YlcQXiowHgdX6.jpg",
      original_language: "en",
      original_title: "Aquaman",
      genre_ids: [28, 12, 14],
      backdrop_path: "/5A2bMlLfJrAfX9bqAibOL2gCruF.jpg",
      adult: false,
      overview:
        "Once home to the most advanced civilization on Earth, the city of Atlantis is now an underwater kingdom ruled by the power-hungry King Orm. With a vast army at his disposal, Orm plans to conquer the remaining oceanic people -- and then the surface world. Standing in his way is Aquaman, Orm's half-human, half-Atlantean brother and true heir to the throne. With help from royal counselor Vulko, Aquaman must retrieve the legendary Trident of Atlan and embrace his destiny as protector of the deep.",
      release_date: "2018-12-07"
    },
    {
      vote_count: 193,
      id: 512196,
      video: false,
      vote_average: 6.2,
      title: "Happy Death Day 2U",
      popularity: 95.233,
      poster_path: "/whtt9F8PFqvEgc4fDSHZPkitFk4.jpg",
      original_language: "en",
      original_title: "Happy Death Day 2U",
      genre_ids: [27, 9648, 53, 878, 35],
      backdrop_path: "/7trJGwprMUMKhvSx94lmsq6d985.jpg",
      adult: false,
      overview:
        "Collegian Tree Gelbman wakes up in horror to learn that she's stuck in a parallel universe. Her boyfriend Carter is now with someone else, and her friends and fellow students seem to be completely different versions of themselves. When Tree discovers that Carter's roommate has been altering time, she finds herself once again the target of a masked killer. When the psychopath starts to go after her inner circle, Tree soon realizes that she must die over and over again to save everyone.",
      release_date: "2019-02-13"
    },
    {
      vote_count: 133,
      id: 438650,
      video: false,
      vote_average: 5.2,
      title: "Cold Pursuit",
      popularity: 94.934,
      poster_path: "/hXgmWPd1SuujRZ4QnKLzrj79PAw.jpg",
      original_language: "en",
      original_title: "Cold Pursuit",
      genre_ids: [53, 28, 18],
      backdrop_path: "/7Wg6FOEvhduISlxSzSCutAl4lPq.jpg",
      adult: false,
      overview:
        "Nels Coxman's quiet life comes crashing down when his beloved son dies under mysterious circumstances. His search for the truth soon becomes a quest for revenge as he seeks coldblooded justice against a drug lord and his inner circle.",
      release_date: "2019-02-07"
    },
    {
      vote_count: 19,
      id: 390634,
      video: false,
      vote_average: 4.2,
      title: "Fate/stay night: Heaven’s Feel II. lost butterfly",
      popularity: 94.438,
      poster_path: "/4tS0iyKQBDFqVpVcH21MSJwXZdq.jpg",
      original_language: "ja",
      original_title:
        "劇場版「Fate/stay night [Heaven's Feel] ⅠⅠ. lost butterfly」",
      genre_ids: [16, 28, 14, 12],
      backdrop_path: "/3haESpzscyP1pLl2BxQ9j5KK9cM.jpg",
      adult: false,
      overview:
        'Theatrical-release adaptation of the visual novel "Fate/stay night", following the third and final route. (Part 2 of a trilogy.)',
      release_date: "2019-01-12"
    },
    {
      vote_count: 10826,
      id: 284054,
      video: false,
      vote_average: 7.4,
      title: "Black Panther",
      popularity: 92.313,
      poster_path: "/uxzzxijgPIY7slzFvMotPv8wjKA.jpg",
      original_language: "en",
      original_title: "Black Panther",
      genre_ids: [28, 12, 14, 878],
      backdrop_path: "/6ELJEzQJ3Y45HczvreC3dg0GV5R.jpg",
      adult: false,
      overview:
        "King T'Challa returns home from America to the reclusive, technologically advanced African nation of Wakanda to serve as his country's new leader. However, T'Challa soon finds that he is challenged for the throne by factions within his own country as well as without. Using powers reserved to Wakandan kings, T'Challa assumes the Black Panther mantel to join with girlfriend Nakia, the queen-mother, his princess-kid sister, members of the Dora Milaje (the Wakandan 'special forces') and an American secret agent, to prevent Wakanda from being dragged into a world war.",
      release_date: "2018-02-13"
    },
    {
      vote_count: 728,
      id: 375588,
      video: false,
      vote_average: 5.7,
      title: "Robin Hood",
      popularity: 86.408,
      poster_path: "/AiRfixFcfTkNbn2A73qVJPlpkUo.jpg",
      original_language: "en",
      original_title: "Robin Hood",
      genre_ids: [12, 28, 53],
      backdrop_path: "/AuA50D7T7S7OEVcGo0ZKaMhERn0.jpg",
      adult: false,
      overview:
        "A war-hardened Crusader and his Moorish commander mount an audacious revolt against the corrupt English crown.",
      release_date: "2018-11-20"
    },
    {
      vote_count: 271,
      id: 522681,
      video: false,
      vote_average: 6.1,
      title: "Escape Room",
      popularity: 86.36,
      poster_path: "/8yZAx7tlKRZIg7pJfaPhl00yHIQ.jpg",
      original_language: "en",
      original_title: "Escape Room",
      genre_ids: [27, 53, 28],
      backdrop_path: "/mWLljCmpqlcYQh7uh51BBMwCZwN.jpg",
      adult: false,
      overview:
        "Six strangers find themselves in circumstances beyond their control, and must use their wits to survive.",
      release_date: "2019-01-03"
    }
  ]
};
